// Selectors extracted from HomePage.ts and AccountsPage.ts
export const selectors = {
  home: {
    accountsModuleLink: "//a[@title='Accounts']/span[text()='Accounts']",
    newAccountBtn: "//a[@title='New']/div[@title='New']",
  },

  accounts: {
    accountNameInput: 'input[class="slds-input"][name="Name"][part="input"]',
    accountNumberInput: 'input[name="AccountNumber"][class="slds-input"][part="input"]',
    siteInput: 'input[name="Site"][class="slds-input"][type="text"]',
    typeDDBtn: 'button[data-value="--None--"][aria-label="Type"][type="button"]',
    typeDDItem: (index: number) => `//div[@aria-label='Type']/lightning-base-combobox-item[${index}]`,
    annualRevenueInput: 'input[name="AnnualRevenue"][inputmode="decimal"]',
    ratingDDBtn: 'button[aria-label="Rating"][role="combobox"]',
    ratingDDItem: (index: number) => `//div[@aria-label='Rating']/lightning-base-combobox-item[${index}]`,
    phoneInput: 'input[name="Phone"][type="text"][class="slds-input"]',
    faxInput: "input[name='Fax'][type='text'][class='slds-input']",
    websiteInput: 'input[name="Website"][type="text"][class="slds-input"]',
    tickerSymbolInput: 'input[name="TickerSymbol"][type="text"][class="slds-input"]',
    ownershipDDBtn: 'button[aria-label="Ownership"][role="combobox"][data-value="--None--"]',
    ownershipDDItem: (index: number) => `//div[@aria-label="Ownership"]/lightning-base-combobox-item[${index}]`,
    employeesInputRole: { role: "spinbutton" as const, name: "Employees" },
    sicCodeLabelText: "SIC Code",
    billingCountryDDBtn: 'input[aria-label="Billing Country"][data-value="--None--"][autocomplete="country"]',
    billingCountryDDItem: (index: number) => `//div[@aria-label="Billing Country"]/lightning-base-combobox-item[${index}]`,
    streetInput: 'textarea[name="street"][autocomplete="street-address"]',
    billingCityInput: '//label[text()="Billing City"]/following-sibling::div/input[@name="city" and @autocomplete="address-level2"]',
    billingZipInput: '//label[text()="Billing Zip/Postal Code"]/following-sibling::div/input[@name="postalCode" and @autocomplete="postal-code"]',
    shippingCountryDDBtn: 'input[aria-label="Shipping Country"][data-value="--None--"][role="combobox"]',
    shippingCountryDDItem: (index: number) => `//div[@aria-label="Shipping Country"]/lightning-base-combobox-item[${index}]`,
    shippingCityInput: '//label[text()="Shipping City"]/following-sibling::div/input[@name="city" and @autocomplete="address-level2"]',
    shippingZipInput: '//label[text()="Shipping Zip/Postal Code"]/following-sibling::div/input[@name="postalCode" and @autocomplete="postal-code"]',
    customerPriorityDDBtn: 'button[aria-label="Customer Priority"][data-value="--None--"]',
    customerPriorityDDItem: (index: number) => `//div[@aria-label="Customer Priority"]/lightning-base-combobox-item[${index}]`,
    slaExpirationDateInput: 'input[name="SLAExpirationDate__c"]',
    numberOfLocationsInput: 'input[name="NumberofLocations__c"][inputmode="decimal"][type="text"]',
    activeDDBtn: 'button[aria-label="Active"][data-value="--None--"][role="combobox"]',
    activeDDItem: (index: number) => `//div[@aria-label="Active"]/lightning-base-combobox-item[${index}]`,
    slaDDBtn: 'button[aria-label="SLA"][data-value="--None--"][role="combobox"]',
    slaDDItem: (index: number) => `//div[@aria-label="SLA"]/lightning-base-combobox-item[${index}]`,
    slaSerialNumberInput: 'input[name="SLASerialNumber__c"][type="text"][maxlength="10"]',
    upsellDDBtn: 'button[aria-label="Upsell Opportunity"][data-value="--None--"]',
    upsellDDItem: (index: number) => `//div[@aria-label="Upsell Opportunity"]/lightning-base-combobox-item[${index}]`,
    descriptionInput: 'textarea[part="textarea"][maxlength="32000"]',

    saveBtn: 'button[name="SaveEdit"][type="button"]',
    createdToast: "was created",
    savedToast: "was saved",
    deletedToast: "was deleted",

    fileInput: 'input[type="file"]',
    uploadDoneBtn: "//button[contains(@class,'desktop uiButton--default')]/span[text()='Done']",
    uploadedToast: "was uploaded",

    firstRowCell: "//tbody[contains(@style,'counter-reset: row-number 0')]/tr[1]/td[6]",
    firstRowMenuItem: "//ul[@class='scrollable' and @role='presentation']/li[1]",

    showMoreActionsBtn: "//span[text()='Show more actions']",
    deleteActionMenuItem: 'runtime_platform_actions-action-renderer[title="Delete"][apiname="Delete"]',
    deleteConfirmBtn: "//div[contains(@class,'forceModalActionContainer--footerAction')]/button[@title='Delete']",

    requiredFieldError: "//*[normalize-space(text())='Complete this field.']",
    errorIcon: 'lightning-primitive-icon[variant="error"][exportparts="icon"]',
  },
};
